---
title: "OpenAlex data at SUNET"
date: today
format:
  revealjs:
    theme: solarized
    transition: slide
    slide-number: true
    controls: true
    progress: true
    center: true
    width: 960
    height: 700
---

# Agenda

1. Status och läge hos resp. organisation

2. Resurser & engagemang

3. Vad vill vi uppnå i närtid?

4. Metoder för primär inläsning av utplattning av json  
  konkret första område att utvärdera?

# Överblick & status KTH

- Dialog med Sunet under våren

- Server uppe från maj

- Första tester av tjänst + datadump därefter

- Preliminärt avtal under juni

# openalex.sunet.se 

- **Miljö hos SUNET för en server**
  - Spegling av snapshotdata från AWS S3 openalex snapshot
  - Schemalagd synk (openalex uppdaterar snapshot:et månadsvis för premium subscriptions)
  - Processer för att omvandla .jsonl till tabulärt format
  - inga försök att ladda som formell databas 
  
# openalex.sunet.se 

- **Kapacitet**
  - "demetrius" har 16 vCPUs och 32 GB RAM
  - 2,8TB lokal disk
  - Använder Sunet S3-lagring för speglingen
  - Använder "duckdb" för bearbetning (json -> parquet etc)


# Frågor om behov och perspektiv

- Vilka perspektiv finns hos de olika lärosätena? Vad är viktigast i sammanhanget?
- Tankar kring semantiskt lager / "datalake"  ( se https://ducklake.select)
- Synen på normalisering (på rätt nivå)?

# Frågor om dataflöden mm

- Hur skulle man vilja arbeta i praktiken? 
- Ansats vid rektangularisering av data?
- Behov av att kombinera mot "stängd" data från eget lärosäte?


# Behov / önskemål kring åtkomst:

- API (demo, se https://openalex.duckdns.org/api/)
- Databaskopplingar?
- Överföringar av lärosätesspecifika referensdataset

        select * from topics;
        select * from works;
        select * from authors;
        select * from venues;

- Bredare datakälla? SwePub?
