---
title: 'Demo #6 - ABM project'
author: "KTH Library & ITA - ABM project"
date: '2021-03-25'
output:
  ioslides_presentation:
    css: assets/css/styles.css
    logo: assets/img/logo.svg
    mathjax: default
    self-contained: yes
    transition: slower
    widescreen: yes
  beamer_presentation: default
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(ktheme)
library(webshot)
library(DT)
library(ggplot2)
library(reshape2)
library(formattable)
library(readxl)
library(dplyr)

red <- function(txt) 
  sprintf("<font color='%s'>\n%s\n</font>", tolower(palette_kth()["cerise"]), txt)

#webshot::install_phantomjs()
#unlink("retrosearch-screenshot.png")

suppressPackageStartupMessages(library(magick))

# BG images that could be used

```

## Background for ABM project

**Goal:** 

> 1. Replace the previous ABM i.e. Annual Bibliometric Monitoring / Årlig Bibliometrisk Uppföljning at KTH
> 2. Further develop the ABM based on input from this group

**Summary:**

Our [previous demo meeting](https://KTH-Library.github.io/demo-5) was held 2020-11-10. After christmas vacations we have worked on Sprints **24 to 31** (current).

**Netiquette:**

Please use Zoom, raise hand for questions or write in the chat, mute if not speaking, and think about questions for the Q&A session at the end.

## Agenda {data-background=assets/bg/kth-6.png data-background-size=cover}

- Recap from previous meetings - What **feedback** has been given so far in the project?

- Progress - What is **new** since last meeting?

- A **demo** presenting new work (based on 2020 data update)

- Update about **other efforts** (data integration, APIs etc)

- Your **questions and feedback**

## Demo group feedback

You have provided many suggestions about steps forward, beyond the "old" ABM application.

Here is a rough attempt to summarize input since the project start into some themes:

- One theme has been **Scopus data** and its inclusion in ABM

- Another theme has been about presenting **results at division level** in an author-based variant of ABM that focuses more a "current view"

- **User Experience improvements** with closer alignment with KTH Style on the web

- Addition of **Open Access data/reports** including Altmetric integration

## Feedback Recap (continued ...)

- Data integration against **other (non-WoS) sources** has been a reoccurring theme
  - Requests regarding Google Scholar, Microsoft Academic, Semantic Scholar etc and ORCID matching (added in Kontarion and DiVA package)
  - Coverage for conference proceedings in CS (partially addressed by Scopus)
  - Custom "divisions" with arbitrary researchers (a POC experiment made in separate app)

- Another theme has been ideas about new ways to interactively **access, view and explore** the ÅBU data
  - Data Quality and Curation aspects, for example for usage of HR / researcher data from KTH 
  - Raw data access, APIs (mostly non-public APIs due to usage rights for WoS and Scopus data)

## Progress - What is new during Q1? {data-background=assets/bg/plant.png data-background-size=cover}

- Data update with `r red("updated data for 2013-2019")` including RAE data delivery

- Data integration for `r red("Scopus data")` added

- Addition of `r red("author-based report with output at divisional level")` based on KTH HR-data

- Brief `r red("interpretation and comparison of results")` based on new data for 2020

- New `r red("Open Access report")` included - what does it say?

- Other `r red("related efforts")` (non-app-specific)

# Demo

  - **ABM updated with data for 2013-2019**(https://abm.sys.kth.se/public/)
  - **Scopus** in ABM
  - **Author-based ABM** (https://bibliometrics.lib.kth.se/beta/authorbased)
  - Research-oriented divisions based on HR/UG-data
  - New OA report - link added

## Interpretation of **results**

TODO: revise and adapt this...

- How does results based on Scopus and WoS differ - beyond coverage? Explanation?
- Comparison organizational based ABM vs author-based - follow-up to previous comparison?
- What patterns can we see? Trends over time?
- Highlights and deviations
- Merging organizational units - how does it affect results?

## WoS vs Scopus

- Additional help in interpretation 
- Differences in coverage
- Note different standardization groups - what does different indicator values mean?

## Regular ABM vs staff-based version

- Different scopes of applications
- ...

## Other efforts

- All efforts are available at [KTH-Library@GitHub](https://github.com/kth-library)

- API and Static site generation used for deploying author-based ABM

- New python tools [`bibutils`](https://github.com/KTH-Library/bibutils) for Data Quality and Curation

- A new R package [`diva`](https://gita.sys.kth.se/kthb/diva) with Data Quality/Curation tooling for the KTH corpus (publications and authors)

- A new R package [`cordis`](https://github.com/KTH-Library/cordis) provides data access to EU data for research projects, including a new data-only repository ['cordis-data`](https://github.com/KTH-Library/cordis-data), piggybacking on GitHub, using it for storing releases of versioned data publicly.

- Integration with HR data (SFTP site with extracts) flowing into modern object storage (using https://min.io/).

# Going forward

## Going forward

- Focusing on additions to collaboration data
- Suggestion:   
    * Add coarse organization overview (as table) to ABM
    * Further collaboration data presented through separate application
- Working more in practice with new HR-data resource

# Questions and feedback

## Questions and Answers

Please provide your input!

- Do you think the what was presented in the demonstration meets your needs for **Scopus data** in ABM?
- What advantages and disadvantages do you see with introducing these **additional dimensions** into ABM (more data sources, author-based variant)?
- Other questions from the Zoom chat
- Suggestions and comments

Thank you for attending!
