version: '3.7'

services:
  light:
    image: kthb/kontarion:apidemo
    ports:
      - 80:8080
    command: Rscript /tmp/kthb_start_api.R
    volumes:
      - ./kthb_light_api.R:/tmp/kthb_light_api.R:ro
      - ./kthb_start_api.R:/tmp/kthb_start_api.R:ro

