version: '3.1'

services:

  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password

  maria:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=example

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=example
#    ports:
#      - 5432:5432
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./bibmon.sql:/docker-entrypoint-initdb.d/z_bibmon.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=markussk@kth.se
      - PGADMIN_DEFAULT_PASSWORD=password12
    ports:
      - 80:80
    depends_on:
      - db

  pgloader:
    image: dimitri/pgloader:ccl.latest
#    command: bash -c "sleep 10 && pgloader /tmp/bibmon.db postgresql://postgres:example@db/"
    volumes:
      - ./bibmon.db:/tmp/bibmon.db
    depends_on:
      - db

  zeppelin:
    image: apache/zeppelin:0.8.2
    environment:
      - ZEPPELIN_ADDR=0.0.0.0
    depends_on:
      - db
    ports:
      - 10000:8080

