library(magick)
library(here)
library(magrittr)

# KTH login screen logo

#imgurl_src <- "https://kth-library.github.io/assets/img/logo.png"

# the kth-logo-cirle is generated by this command 
# (requires imagemagick ie sudo apt install imagemagick-6.q16)
# convert -size 1186x1186 xc:none -fill kth-logo.png -draw "translate 593,593 circle 0,0 593,0" kth-logo-circle.png

"https://www.kth.se/polopoly_fs/1.77257.1550147376!/KTH_Logotyp_RGB_2013-2.svg" %>%
  image_read_svg(width = 480, height = 480) %>%
  image_convert(format = "png") %>%
  image_resize("240x240") %>%
  image_write(path = file.path(here(), "assets", "img", "logo-square.png"))